package com;
import com.microsoft.playwright.*;
import com.microsoft.playwright.options.*;
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;
import java.util.*;
import java.util.regex.Pattern;

public class FreeUserPlayGame {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
        .setHeadless(false));
      BrowserContext context = browser.newContext(new Browser.NewContextOptions()
        .setViewportSize(1000, 700));
      Page page = context.newPage();
      page.navigate("https://awspf.com/");
      page.locator("form").getByRole(AriaRole.LINK, new Locator.GetByRoleOptions().setName("Browse All Games")).click();
      page.navigate("https://awspf.com/search");
      page.locator("form div").click();
      page.getByPlaceholder("Search Games").fill("7th Grade Math");
      page.getByPlaceholder("Search Games").press("Enter");
      assertThat(page.getByText("7th Grade Math", new Page.GetByTextOptions().setExact(true))).isVisible();
      Page page1 = page.waitForPopup(() -> {
        page.locator(".game-card-footer__btn").first().click();
      });
      page1.locator("div").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^Flashcards Self-Paced Review$"))).nth(2).click();
      assertThat(page1.getByText("UPGRADE toPROGraduate from")).isVisible();
      assertThat(page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Go Pro"))).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close")).click();
      page1.locator("div").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^Choice Jeopardy-style Multiple Choice$"))).nth(2).click();
      assertThat(page1.getByText("UPGRADE toPROGraduate from")).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close")).click();
      page1.getByText("Quiz Bowl College Bowl-style").click();
      assertThat(page1.getByText("UPGRADE toPROGraduate from")).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close")).click();
      page1.locator("div").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^Interactive Choice Self-Paced Jeopardy-style Multiple Choice$"))).nth(2).click();
      assertThat(page1.getByText("UPGRADE toPROGraduate from")).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close")).click();
      page1.locator("div").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^Memory Tile Matching Memory Board$"))).nth(2).click();
      assertThat(page1.getByText("UPGRADE toPROGraduate from")).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close")).click();
      page1.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Factile Jeopardy-style    ")).click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("6").setExact(true)).click();
      assertThat(page1.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("Do you want to select more no"))).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Cancel")).click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("5").setExact(true)).click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("No")).click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Auto Select")).click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Begin Game")).click();
      page1.locator(".gamePointsBlock").first().click();
      page1.locator(".podium-controls > i").first().click();
      assertThat(page1.locator("#game-screen-bottom")).containsText("$100");
      assertThat(page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue "))).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("span:nth-child(3) > .gamePointsBlock").first().click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      assertThat(page1.locator("#game-screen-bottom")).containsText("$200");
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator(".gameCategoryColumn > span:nth-child(4)").first().click();
      //page1.locator("body").press("AudioVolumeDown");
      page1.locator(".podium-controls > i").first().click();
      assertThat(page1.locator("#game-screen-bottom")).containsText("$400");
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("span:nth-child(5)").first().click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      assertThat(page1.locator("#game-screen-bottom")).containsText("$400");
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("span:nth-child(6)").first().click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      assertThat(page1.locator("#game-screen-bottom")).containsText("$900");
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(2) > span:nth-child(2)").click();
      assertThat(page1.getByText("-4+")).isVisible();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      assertThat(page1.getByText("$300")).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(2) > span:nth-child(3) > .gamePointsBlock").click();
      page1.locator("div:nth-child(4) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(2) > span:nth-child(4) > .gamePointsBlock").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(2) > span:nth-child(5) > .gamePointsBlock").click();
      assertThat(page1.locator("#responsive-question")).containsText("-4+-5/2");
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      assertThat(page1.locator("#game-screen-bottom")).containsText("$1300");
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(2) > span:nth-child(6)").click();
      page1.locator("div:nth-child(4) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(3) > span:nth-child(2) > .gamePointsBlock").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(3) > span:nth-child(3) > .gamePointsBlock").click();
      page1.locator(".podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(3) > span:nth-child(4) > .gamePointsBlock").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(3) > span:nth-child(5) > .gamePointsBlock").click();
      assertThat(page1.getByText("$1600")).isVisible();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i:nth-child(2)").click();
      assertThat(page1.getByText("$1200")).isVisible();
      page1.locator("div:nth-child(4) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(3) > span:nth-child(6) > .gamePointsBlock").click();
      page1.locator(".podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(4) > span:nth-child(2) > .gamePointsBlock").click();
      page1.locator("div:nth-child(4) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(4) > span:nth-child(3)").click();
      page1.locator(".podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(4) > span:nth-child(4) > .gamePointsBlock").click();
      page1.getByText("Skip/See Answer").click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(4) > span:nth-child(5)").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(4) > span:nth-child(6)").click();
      page1.locator("div:nth-child(4) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(5) > span:nth-child(3) > .gamePointsBlock").click();
      page1.locator(".podium-controls").first().click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(5) > span:nth-child(4)").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(5) > span:nth-child(2) > .gamePointsBlock").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(5) > span:nth-child(5) > .gamePointsBlock").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(5) > span:nth-child(6)").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(6) > span:nth-child(2) > .gamePointsBlock").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(6) > span:nth-child(5) > .gamePointsBlock").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(6) > span:nth-child(4) > .gamePointsBlock").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls").click();
      page1.locator(".podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(6) > span:nth-child(3) > .gamePointsBlock").click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      page1.locator("div:nth-child(6) > span:nth-child(6)").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      assertThat(page1.getByText("Enter Valid Wagers")).isVisible();
      page1.getByPlaceholder("0").first().click();
      page1.getByPlaceholder("0").first().fill("1300");
      page1.getByPlaceholder("0").nth(1).click();
      page1.getByPlaceholder("0").nth(1).fill("1000");
      page1.getByPlaceholder("0").nth(2).click();
      page1.getByPlaceholder("0").nth(2).fill("1200");
      page1.getByPlaceholder("0").nth(3).click();
      page1.getByPlaceholder("0").nth(3).fill("495");
      page1.getByText("It's Final Factile Time!7th").click();
      page1.getByRole(AriaRole.IMG, new Page.GetByRoleOptions().setName("Avatar")).click();
      page1.getByRole(AriaRole.IMG, new Page.GetByRoleOptions().setName("Avatar")).click();
      page1.getByPlaceholder("0").click();
      page1.getByPlaceholder("0").fill("0");
      page1.getByPlaceholder("0").press("Enter");
      page1.getByText("It's Final Factile Time!7th").click();
      assertThat(page1.locator("#playFinalJeopardy")).isVisible();
      page1.locator("#playFinalJeopardy").click();
      assertThat(page1.getByText("What is big and yellow and")).isVisible();
      page1.locator(".carousel-arrow-left > span > .fa").click();
      page1.locator("div:nth-child(3) > .podium-content > .podium-controls > i").first().click();
      page1.locator("div:nth-child(2) > .podium-content > .podium-controls > i").first().click();
      page1.locator("i:nth-child(2)").first().click();
      page1.locator("div:nth-child(4) > .podium-content > .podium-controls > i").first().click();
      page1.locator("i:nth-child(2)").click();
      assertThat(page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Reveal Answer"))).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Reveal Answer")).click();
      assertThat(page1.getByText("What is a school bus?")).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Continue ")).click();
      assertThat(page1.getByText("Winner")).isVisible();
     // assertThat(page1.getByRole(AriaRole.IMG, new Page.GetByRoleOptions().setName("Sea Shell"))).isVisible();
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Show Score")).click();
      assertThat(page1.getByText("Team Scores")).isVisible();
      assertThat(page1.locator("tbody")).containsText("4100");
      page1.getByRole(AriaRole.CELL, new Page.GetByRoleOptions().setName("MIA").setExact(true)).click();
      //assertThat(page1.getByRole(AriaRole.CELL, new Page.GetByRoleOptions().setName("JAYLEN").setExact(true))).isVisible();
      //assertThat(page1.getByRole(AriaRole.CELL, new Page.GetByRoleOptions().setName("TOMATO").setExact(true))).isVisible();
      //assertThat(page1.getByRole(AriaRole.CELL, new Page.GetByRoleOptions().setName("CELERY").setExact(true))).isVisible();
      page1.locator("button").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^Close$"))).click();
    }
  }
}