package com;

import java.io.IOException;
import java.util.regex.Pattern;

import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.AriaRole;

import Resource.BaseTest;

public class TestPreview extends BaseTest {

	@Test(priority=1)
	public void test_preview_Public_Game() throws IOException, InterruptedException {
		Thread.sleep(2000);
		  page.navigate(properties.getProperty("rootUrl"));
		  page.waitForNavigation(() -> 
	      page.locator("//*[@id=\"gatsby-focus-wrapper\"]/div/main/section[1]/div/div/div[1]/div/div[1]/a[2]").click());

      //page.getByRole(AriaRole.MAIN).getByRole(AriaRole.LINK, new Locator.GetByRoleOptions().setName("Log In")).click();
      page.getByPlaceholder("Email Id or Username").click();
      page.getByPlaceholder("Email Id or Username").fill("sunita1.deligence@gmail.com");
      page.getByPlaceholder("Password").click();
      page.getByPlaceholder("Password").fill("123456");
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Log In")).click();
      page.getByText("Public Games", new Page.GetByTextOptions().setExact(true)).click();
      page.getByPlaceholder("Search in Public Games").click();
      page.getByPlaceholder("Search in Public Games").fill("7th grade math");
      Thread.sleep(2000);      
      page.locator("form").getByRole(AriaRole.BUTTON).first().click();    
      Thread.sleep(2000); 
     page.locator(".game-card-footer > button").first().click();
    //  page.getByText("Integers").click();
     // assertThat(page.getByText("Integers")).isVisible();
      page.locator(".gamePointsBlock").first().click();
      assertThat(page.getByText("-9+-(-5)")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is -4?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 15?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("+6")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("-6-(-8)")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is 2?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is -9?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("-9+9+-9+9+-")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("-(-1000)-")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is 996?")).isVisible();
      page.getByLabel("right navigationBtns").click();
      assertThat(page.getByText("What is 17?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("-5+4+6*9/")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.locator("#responsive-question")).containsText("-4+-5/2");
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is -6.5?")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("What is 5.222 infinite?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("9d-25=")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("2x + 7 =")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is 4?")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("What is 3?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("-4+")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      page.getByLabel("right navigationBtns").click();
      assertThat(page.getByText("What is y≥1/6?")).isVisible();
      assertThat(page.getByText("What is y≥1/6?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is x≤2?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is z≤33?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is y≤5.61616161 infinite?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is x≥174?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("x/6-5≥")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("99y≤")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("3z≤")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("54x≤")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("+6y≥24")).isVisible();
      page.getByLabel("right navigationBtns").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is 0.1?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 5.94?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 7.02?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is $32.10?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("Larry bought $30.00 worth of")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("9% of")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("23% of")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("6% of")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("Convert 10% to a decimal")).isVisible();
      page.getByLabel("right navigationBtns").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is -20?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is -339?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 8?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 15?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is -")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("-9(60+95)")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("(2-3) + (20-4)")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("- 4 - 2")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("-7(56-7)")).isVisible();
      page.getByLabel("up navigationBtns").click();
      assertThat(page.getByText("-30-20-10")).isVisible();
      page.getByLabel("right navigationBtns").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is 133.333 infinite?")).isVisible();
      assertThat(page.getByText("What is 133.333 infinite?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 1.897?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 1.25?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 41?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is 9.2?")).isVisible();
      page.getByLabel("down navigationBtns").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("What is big and yellow and")).isVisible();
      page.getByLabel("down navigationBtns").click();
      page.locator("div").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^FF$"))).nth(2).click();
      page.locator("div:nth-child(6) > span").first().click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      page.locator("div:nth-child(6) > span:nth-child(2)").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      page.locator("div:nth-child(6) > span:nth-child(3)").click();
      page.locator("div:nth-child(6) > span:nth-child(4)").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      page.locator("div:nth-child(6) > span").first().click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Question")).click();
      assertThat(page.getByText("What is the unit rate of")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("into 74")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("into 45")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("5 into")).isVisible();
      page.getByLabel("down navigationBtns").click();
      assertThat(page.getByText("What is the unit rate if 5")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Final Factile")).click();
      assertThat(page.getByText("What is big and yellow and")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("See Answer")).click();
      assertThat(page.getByText("What is a school bus?")).isVisible();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close")).click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Factile Logo My Games")).click();
      page.locator("#sidebar-nav__item-myGames").getByText("My Games").click();
      Thread.sleep(2000);
      
      
	}}
      
    